### ISSUE TITLE
Release 0.2.0

### ISSUE THREAD

**Issue by agconti** [agconti/cookiecutter-es6-boilerplate#24]
- [x] Add z-index framework #18
- [x] Add basic color configuration #19
- [x] Add basic css transition easings #17
- [x] Add project level ci setup #29
- [x] Add travis badge to project ReadMe #31
