### ISSUE TITLE
Release 0.3.0

### ISSUE THREAD

**Issue by agconti** [agconti/cookiecutter-es6-boilerplate#33]
- [ ] Implement a simple node server to serve app #16
- [ ] Update project's feature list #34
- [ ] Add javascript linter #35
- [ ] Add typography setup #37
- [ ] Add generic style guide setup #36
- [x] Add unit testing support with mocha and chai #38
- [ ] Rename gulp static files tasks to assets to improve readability #46
- [ ] Add sass linter #49
- [x] Fix build:static task to call buildStatic instead of buildScss #50
