### ISSUE TITLE
Release 0.1.0

### ISSUE THREAD

**Issue by agconti** [agconti/cookiecutter-es6-boilerplate#4]
- [x] Add contributing guidlines #5
- [x] create gh-pages for the project #3 
- [x] Update ReadMe with overview #2 
- [x] Update ReadMe with feature list #1
- [x] Add gif of scaffolding to README #8
- [x] Add gulp-sass error handling #9
- [x] Add `gulp-babel` error handling #11
- [x] Split gulpfile tasks into separate files #13 
- [x] Allow `watch:js` to continue after it encounters an error #14 
- [x] Update gif since record.it gif is not permeant. #22
